# Generated by Django 5.1.4 on 2025-02-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_data_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='first_name',
            field=models.CharField(default='Test name', max_length=64),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='last_name',
            field=models.CharField(default='Test surname', max_length=64),
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='author.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='BiographyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.ManyToManyField(to='author.authormodel')),
            ],
        ),
    ]
