# Generated by Django 5.1.4 on 2025-02-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_authormodel_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='name',
            new_name='name_article',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='name_book',
        ),
    ]
