# Generated by Django 5.1.4 on 2025-03-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_rename_name_articlemodel_name_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='author.authormodel', verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='name_article',
            field=models.CharField(max_length=256, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='birthday_year',
            field=models.PositiveIntegerField(verbose_name='Год рождения автора'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='first_name',
            field=models.CharField(default='Test name', max_length=64, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='last_name',
            field=models.CharField(default='Test surname', max_length=64, verbose_name='Фамилия автора'),
        ),
        migrations.AlterField(
            model_name='biographymodel',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.authormodel', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='biographymodel',
            name='text',
            field=models.TextField(verbose_name='Текст биографии'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ManyToManyField(to='author.authormodel', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name_book',
            field=models.CharField(max_length=128, verbose_name='Название книги'),
        ),
    ]
