# Generated by Django 5.1.4 on 2025-01-03 20:43

from django.db import migrations

def forward_func(apps, schema_editor):
    author_model = apps.get_model('author', 'AuthorModel')
    first_names = ['Иван', 'Пётр']
    last_names = ['Иванов', 'Сергеев']
    years = [1995, 2000]
    for i in range(2):
        author_model.objects.create(
            first_name = first_names[i],
            last_name = last_names[i],
            birthday_year = years[i]
        )

def reverse_func(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
